@startuml
'https://plantuml.com/class-diagram

class ToDoList
{
    main()
    start()
}

class ToDoListDriver
{
    ' Variables
    - inputDate: DatePicker
    - taskDesc: TextField
    - toDoListName: TextField

    ' Table elements
    - listTable: TableView
    - statusList: TableColumn
    - taskList: TableColumn
    - dateList: TableColumn
    - descList: TableColumn

    bufferList: ObservableList
    filtertedList: FilteredList
    -int index


    + addToDoClick()
    + setTheCells()
    + populateBuffer()
    + toDoListSelectClick()
    + removeALLClick()
    + exportAllClick()
    + importClick()
    + filterCompletedClick()
    + filterIncompletedClick()
    + filterDefaultClick()
}

class createToDoList
{
    - String status
    - String name
    - String date
    - String desc

    + createToDoList()

    + setstatus()
    + setName()
    + setDate()
    + setDesc()

    + getStatus()
    + getName()
    + getDate()
    + getDesc()
}


javafx.Application <|-- ToDoList

ToDoList - ToDoListDriver
ToDoListDriver - createToDoList



@enduml